services:
  backend:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Ollama хост на локальной машине
      OLLAMA_HOST: "http://host.docker.internal:11434" # Windows/macOS
      # На Linux можно прописать IP хоста
      # OLLAMA_HOST: "http://172.17.0.1:11434"
    depends_on: []

  bot:
    build: .
    command: python -m bot.app
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - backend
